logo: Judith # add logo name
title: Judith - Enjoy Freedom
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Banner settings
video: mountains.mp4 # add banner video. Add your video file to the folder video
banner-title: The story begins here # add banner title
banner-desc: 爱是我们能感知的，唯一一种超越时空纬度的东西。--《星际穿越》 # add banner description

# Author settings
author-pic: face.jpg # your photo
author-name: Judith Zhu # your name
about-author: I am a clever girl. Sometimes I may be naughty and playful, but my attitude towards  a better life will not change. # about author
email: 7.JudithZhu@gmail.com # your email
phone: (496)-169-6557 # your pnone number
website: https://Judith-Zhu.github.io # you website

# Social link
google_url: mailto:7.JudithZhu@gmail.com    # add url link
twitter_url: https://twitter.com/judithzhu2020   # add url link
instagram_url: https://www.instagram.com/JudithZhu2017 # add url link
pinterest_url: https://www.pinterest.com/JudithZhu2017 # add url link
dribbble_url:  https://dribbble.com/JudithZhu # add url link
facebook_url: https://www.facebook.com/judith.zhu.1044 # add url link

# Disqus
discus_identifier: judith-4 # add your discus identifier.  Not your username.  To get this, register your forum here with a unique ID: https://disqus.com/admin/create/

# Newsletter
mailchimp: # add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e

# Tracker
analytics:

# Paginate
paginate: 12
paginate_path: /page:num/

# Build settings
markdown: kramdown

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]

# admin_plugin
jekyll_admin:
  # hidden_links:
  #   - posts
  #   - pages
  #   - staticfiles
  #   - datafiles
  #   - configuration